### ISSUE TITLE
CSV file path on windows

### ISSUE THREAD

**Issue by bh-ref** [cedricblondeau/magento2-module-catalog-import-command#1]
Hi, 

thank you very much for this module! 

For development, I am using a windows machine. If I am executing 
`php bin/magento catalog:import C:\somePath\catalog_product.csv`
this error message appears:

```
 [LogicException]
 Unable to open file: 'C:\somePath\catalog_product.csv'
```

The command `'directory' => $this->readFactory->create('/')` on line 74 in `Model/Import.php` is the cause of the error. Due to this, the file path is computed as /C:/somePath/catalog_product.csv, but it should be C:/somePath/catalog_product.csv (without a preceeding slash).

My solution was to change that line to 
`'directory' => $this->readFactory->create('')`

And now, it is working fine. However, I have to test later, if that will work on linux, too.

**Comment by bh-ref** [comment]
Alright, I tested my changes on Debian 8 (jessie), it does not work, I have to use your original code. If I will work out a nice detection sometime later, I will come back and post it. Anyway, thanks again for your great work!

**Comment by cedricblondeau** [comment]
Thank you very much for reporting this and for trying to fix it. I appreciate.

Unfortunately, `Magento\ImportExport\Model\Import\Source\Csv` takes a a directory and a file path in its constructor which is not ideal if we need to pass an absolute path (we want to allow import from a CSV file which can be located anywhere on the filesystem).

Extracting parameters using `pathinfo()` function would probably work but it's a bit hacky.

We could also simply extend `Magento\ImportExport\Model\Import\Source\Csv` and introduce a new constructor, so we can pass it a simple `Magento\Framework\Filesystem\File\Write` object but there is maybe a more simple solution.

What do you think?

**Comment by cedricblondeau** [comment]
Should be fine now :).
