### ISSUE TITLE
please make version up

### ISSUE THREAD

**Issue by sawke28** [cedricblondeau/magento2-module-catalog-import-command#2]
hellow
this module seems to be very useful
but i could not install  by composer
because of problems bellow

your need version is 100.0 in composer.json 
"require": {
    "magento/framework": "100.0._",
    "magento/module-import-export": "100.0._"
  },

but my module version is 100.1
$ grep magento/framework composer.json 
        "magento/framework": "100.1.0-rc2",
$ grep magento/module-import-export composer.json 
        "magento/module-import-export": "100.1.0-rc2",

so please make it  version up to 100.1

**Comment by cedricblondeau** [comment]
d914f77
